// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Runtime.InteropServices;
    using System.Collections.Generic;
    using Coherence.ProtocolDef;
    using Coherence.Serializer;
    using Coherence.SimulationFrame;
    using Coherence.Entities;
    using Coherence.Utils;
    using Coherence.Brook;
    using Coherence.Core;
    using Logger = Coherence.Log.Logger;
    using UnityEngine;
    using Coherence.Toolkit;
    public struct _b6b91167bdda7fd42ac20fbdb992aeca_5409921327994379146 : ICoherenceComponentData
    {
        [StructLayout(LayoutKind.Explicit)]
        public struct Interop
        {
            [FieldOffset(0)]
            public Vector3 rootPosition;
            [FieldOffset(12)]
            public Quaternion rootRotation;
            [FieldOffset(28)]
            public System.Byte ToRun;
        }

        public void ResetFrame(AbsoluteSimulationFrame frame)
        {
            FieldsMask |= _b6b91167bdda7fd42ac20fbdb992aeca_5409921327994379146.rootPositionMask;
            rootPositionSimulationFrame = frame;
            FieldsMask |= _b6b91167bdda7fd42ac20fbdb992aeca_5409921327994379146.rootRotationMask;
            rootRotationSimulationFrame = frame;
            FieldsMask |= _b6b91167bdda7fd42ac20fbdb992aeca_5409921327994379146.ToRunMask;
            ToRunSimulationFrame = frame;
        }

        public static unsafe _b6b91167bdda7fd42ac20fbdb992aeca_5409921327994379146 FromInterop(IntPtr data, Int32 dataSize, InteropAbsoluteSimulationFrame* simFrames, Int32 simFramesCount)
        {
            if (dataSize != 29) {
                throw new Exception($"Given data size is not equal to the struct size. ({dataSize} != 29) " +
                    "for component with ID 19");
            }

            if (simFramesCount != 0) {
                throw new Exception($"Given simFrames size is not equal to the expected length. ({simFramesCount} != 0) " +
                    "for component with ID 19");
            }

            var orig = new _b6b91167bdda7fd42ac20fbdb992aeca_5409921327994379146();

            var comp = (Interop*)data;

            orig.rootPosition = comp->rootPosition;
            orig.rootRotation = comp->rootRotation;
            orig.ToRun = comp->ToRun != 0;

            return orig;
        }


        public static uint rootPositionMask => 0b00000000000000000000000000000001;
        public AbsoluteSimulationFrame rootPositionSimulationFrame;
        public Vector3 rootPosition;
        public static uint rootRotationMask => 0b00000000000000000000000000000010;
        public AbsoluteSimulationFrame rootRotationSimulationFrame;
        public Quaternion rootRotation;
        public static uint ToRunMask => 0b00000000000000000000000000000100;
        public AbsoluteSimulationFrame ToRunSimulationFrame;
        public System.Boolean ToRun;

        public uint FieldsMask { get; set; }
        public uint StoppedMask { get; set; }
        public uint GetComponentType() => 19;
        public int PriorityLevel() => 100;
        public const int order = 0;
        public uint InitialFieldsMask() => 0b00000000000000000000000000000111;
        public bool HasFields() => true;
        public bool HasRefFields() => false;


        public long[] GetSimulationFrames() {
            return null;
        }

        public int GetFieldCount() => 3;


        
        public HashSet<Entity> GetEntityRefs()
        {
            return default;
        }

        public uint ReplaceReferences(Entity fromEntity, Entity toEntity)
        {
            return 0;
        }
        
        public IEntityMapper.Error MapToAbsolute(IEntityMapper mapper)
        {
            return IEntityMapper.Error.None;
        }

        public IEntityMapper.Error MapToRelative(IEntityMapper mapper)
        {
            return IEntityMapper.Error.None;
        }

        public ICoherenceComponentData Clone() => this;
        public int GetComponentOrder() => order;
        public bool IsSendOrdered() => false;


        public AbsoluteSimulationFrame? GetMinSimulationFrame()
        {
            AbsoluteSimulationFrame? min = null;


            return min;
        }

        public ICoherenceComponentData MergeWith(ICoherenceComponentData data)
        {
            var other = (_b6b91167bdda7fd42ac20fbdb992aeca_5409921327994379146)data;
            var otherMask = other.FieldsMask;

            FieldsMask |= otherMask;
            StoppedMask &= ~(otherMask);

            if ((otherMask & 0x01) != 0)
            {
                this.rootPositionSimulationFrame = other.rootPositionSimulationFrame;
                this.rootPosition = other.rootPosition;
            }

            otherMask >>= 1;
            if ((otherMask & 0x01) != 0)
            {
                this.rootRotationSimulationFrame = other.rootRotationSimulationFrame;
                this.rootRotation = other.rootRotation;
            }

            otherMask >>= 1;
            if ((otherMask & 0x01) != 0)
            {
                this.ToRunSimulationFrame = other.ToRunSimulationFrame;
                this.ToRun = other.ToRun;
            }

            otherMask >>= 1;
            StoppedMask |= other.StoppedMask;

            return this;
        }

        public uint DiffWith(ICoherenceComponentData data)
        {
            throw new System.NotSupportedException($"{nameof(DiffWith)} is not supported in Unity");
        }

        public static uint Serialize(_b6b91167bdda7fd42ac20fbdb992aeca_5409921327994379146 data, bool isRefSimFrameValid, AbsoluteSimulationFrame referenceSimulationFrame, IOutProtocolBitStream bitStream, Logger logger)
        {
            if (bitStream.WriteMask(data.StoppedMask != 0))
            {
                bitStream.WriteMaskBits(data.StoppedMask, 3);
            }

            var mask = data.FieldsMask;

            if (bitStream.WriteMask((mask & 0x01) != 0))
            {
                var fieldValue = (data.rootPosition.ToCoreVector3());
                bitStream.WriteVector3(fieldValue, FloatMeta.NoCompression());
            }
            mask >>= 1;
            if (bitStream.WriteMask((mask & 0x01) != 0))
            {
                var fieldValue = (data.rootRotation.ToCoreQuaternion());
                bitStream.WriteQuaternion(fieldValue, 32);
            }
            mask >>= 1;
            if (bitStream.WriteMask((mask & 0x01) != 0))
            {
                var fieldValue = data.ToRun;
                bitStream.WriteBool(fieldValue);
            }
            mask >>= 1;

            return mask;
        }

        public static _b6b91167bdda7fd42ac20fbdb992aeca_5409921327994379146 Deserialize(AbsoluteSimulationFrame referenceSimulationFrame, InProtocolBitStream bitStream)
        {
            var stoppedMask = (uint)0;
            if (bitStream.ReadMask())
            {
                stoppedMask = bitStream.ReadMaskBits(3);
            }

            var val = new _b6b91167bdda7fd42ac20fbdb992aeca_5409921327994379146();
            if (bitStream.ReadMask())
            {

                val.rootPosition = bitStream.ReadVector3(FloatMeta.NoCompression()).ToUnityVector3();
                val.FieldsMask |= _b6b91167bdda7fd42ac20fbdb992aeca_5409921327994379146.rootPositionMask;
            }
            if (bitStream.ReadMask())
            {

                val.rootRotation = bitStream.ReadQuaternion(32).ToUnityQuaternion();
                val.FieldsMask |= _b6b91167bdda7fd42ac20fbdb992aeca_5409921327994379146.rootRotationMask;
            }
            if (bitStream.ReadMask())
            {

                val.ToRun = bitStream.ReadBool();
                val.FieldsMask |= _b6b91167bdda7fd42ac20fbdb992aeca_5409921327994379146.ToRunMask;
            }

            val.StoppedMask = stoppedMask;

            return val;
        }


        public override string ToString()
        {
            return $"_b6b91167bdda7fd42ac20fbdb992aeca_5409921327994379146(" +
                $" rootPosition: { this.rootPosition }" +
                $" rootRotation: { this.rootRotation }" +
                $" ToRun: { this.ToRun }" +
                $" Mask: { System.Convert.ToString(FieldsMask, 2).PadLeft(3, '0') }, " +
                $"Stopped: { System.Convert.ToString(StoppedMask, 2).PadLeft(3, '0') })";
        }
    }

}
