// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using Coherence.Toolkit;
    using Coherence.Toolkit.Bindings;
    using Coherence.Entities;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Toolkit.Bindings.ValueBindings;
    using Coherence.Toolkit.Bindings.TransformBindings;
    using Coherence.Connection;
    using Coherence.SimulationFrame;
    using Coherence.Interpolation;
    using Coherence.Log;
    using Logger = Coherence.Log.Logger;
    using UnityEngine.Scripting;
    [UnityEngine.Scripting.Preserve]
    public class Binding_b6b91167bdda7fd42ac20fbdb992aeca_cdc041b020f744e39048b56d0e860565 : PositionBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldPosition);
        public override string CoherenceComponentName => "WorldPosition";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
            set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldPosition)coherenceComponent).value;
            if (!coherenceSync.HasParentWithCoherenceSync) { value += floatingOriginDelta; }

            var simFrame = ((WorldPosition)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldPosition)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldPosition();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_b6b91167bdda7fd42ac20fbdb992aeca_1fa34f402c0e419b8ffc7b6cca012abb : RotationBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldOrientation);
        public override string CoherenceComponentName => "WorldOrientation";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Quaternion Value
        {
            get { return (UnityEngine.Quaternion)(coherenceSync.coherenceRotation); }
            set { coherenceSync.coherenceRotation = (UnityEngine.Quaternion)(value); }
        }

        protected override (UnityEngine.Quaternion value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldOrientation)coherenceComponent).value;

            var simFrame = ((WorldOrientation)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldOrientation)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldOrientation();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_b6b91167bdda7fd42ac20fbdb992aeca_1c230559e37d486e9cf60c58fb35a31b : Vector3Binding
    {   
        private global::UnityEngine.Animator CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Animator)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_b6b91167bdda7fd42ac20fbdb992aeca_5409921327994379146);
        public override string CoherenceComponentName => "_b6b91167bdda7fd42ac20fbdb992aeca_5409921327994379146";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(CastedUnityComponent.rootPosition); }
            set { CastedUnityComponent.rootPosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_b6b91167bdda7fd42ac20fbdb992aeca_5409921327994379146)coherenceComponent).rootPosition;

            var simFrame = ((_b6b91167bdda7fd42ac20fbdb992aeca_5409921327994379146)coherenceComponent).rootPositionSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_b6b91167bdda7fd42ac20fbdb992aeca_5409921327994379146)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.rootPosition = Value;
            }
            else
            {
                update.rootPosition = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.rootPositionSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _b6b91167bdda7fd42ac20fbdb992aeca_5409921327994379146();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_b6b91167bdda7fd42ac20fbdb992aeca_dc5513782f19492f99937b038428d61c : QuaternionBinding
    {   
        private global::UnityEngine.Animator CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Animator)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_b6b91167bdda7fd42ac20fbdb992aeca_5409921327994379146);
        public override string CoherenceComponentName => "_b6b91167bdda7fd42ac20fbdb992aeca_5409921327994379146";
        public override uint FieldMask => 0b00000000000000000000000000000010;

        public override UnityEngine.Quaternion Value
        {
            get { return (UnityEngine.Quaternion)(CastedUnityComponent.rootRotation); }
            set { CastedUnityComponent.rootRotation = (UnityEngine.Quaternion)(value); }
        }

        protected override (UnityEngine.Quaternion value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_b6b91167bdda7fd42ac20fbdb992aeca_5409921327994379146)coherenceComponent).rootRotation;

            var simFrame = ((_b6b91167bdda7fd42ac20fbdb992aeca_5409921327994379146)coherenceComponent).rootRotationSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_b6b91167bdda7fd42ac20fbdb992aeca_5409921327994379146)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.rootRotation = Value;
            }
            else
            {
                update.rootRotation = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.rootRotationSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _b6b91167bdda7fd42ac20fbdb992aeca_5409921327994379146();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_b6b91167bdda7fd42ac20fbdb992aeca_45618c7f21d04c4c8f52d001cceec88b : BoolAnimatorParameterBinding
    {   
        private global::UnityEngine.Animator CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Animator)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_b6b91167bdda7fd42ac20fbdb992aeca_5409921327994379146);
        public override string CoherenceComponentName => "_b6b91167bdda7fd42ac20fbdb992aeca_5409921327994379146";
        public override uint FieldMask => 0b00000000000000000000000000000100;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.GetBool(CastedDescriptor.ParameterHash)); }
            set { CastedUnityComponent.SetBool(CastedDescriptor.ParameterHash, value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_b6b91167bdda7fd42ac20fbdb992aeca_5409921327994379146)coherenceComponent).ToRun;

            var simFrame = ((_b6b91167bdda7fd42ac20fbdb992aeca_5409921327994379146)coherenceComponent).ToRunSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_b6b91167bdda7fd42ac20fbdb992aeca_5409921327994379146)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.ToRun = Value;
            }
            else
            {
                update.ToRun = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.ToRunSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _b6b91167bdda7fd42ac20fbdb992aeca_5409921327994379146();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_b6b91167bdda7fd42ac20fbdb992aeca_7ce3395adfcb4d6ea0475b96cd94994e : StringBinding
    {   
        private global::UnityEngine.UI.Text CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.UI.Text)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_b6b91167bdda7fd42ac20fbdb992aeca_5313132270030033067);
        public override string CoherenceComponentName => "_b6b91167bdda7fd42ac20fbdb992aeca_5313132270030033067";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.String Value
        {
            get { return (System.String)(CastedUnityComponent.text); }
            set { CastedUnityComponent.text = (System.String)(value); }
        }

        protected override (System.String value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_b6b91167bdda7fd42ac20fbdb992aeca_5313132270030033067)coherenceComponent).text;

            var simFrame = ((_b6b91167bdda7fd42ac20fbdb992aeca_5313132270030033067)coherenceComponent).textSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_b6b91167bdda7fd42ac20fbdb992aeca_5313132270030033067)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.text = Value;
            }
            else
            {
                update.text = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.textSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _b6b91167bdda7fd42ac20fbdb992aeca_5313132270030033067();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_b6b91167bdda7fd42ac20fbdb992aeca_fdc8af858f7a4243bbf51f0f7ec2c294 : ByteBinding
    {   
        private global::Y200.ProjectMultiplayer.PlayerSkinManager CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Y200.ProjectMultiplayer.PlayerSkinManager)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_b6b91167bdda7fd42ac20fbdb992aeca_5982182900696927448);
        public override string CoherenceComponentName => "_b6b91167bdda7fd42ac20fbdb992aeca_5982182900696927448";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.Byte Value
        {
            get { return (System.Byte)(CastedUnityComponent.CharacterType); }
            set { CastedUnityComponent.CharacterType = (System.Byte)(value); }
        }

        protected override (System.Byte value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_b6b91167bdda7fd42ac20fbdb992aeca_5982182900696927448)coherenceComponent).CharacterType;

            var simFrame = ((_b6b91167bdda7fd42ac20fbdb992aeca_5982182900696927448)coherenceComponent).CharacterTypeSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_b6b91167bdda7fd42ac20fbdb992aeca_5982182900696927448)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.CharacterType = Value;
            }
            else
            {
                update.CharacterType = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.CharacterTypeSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _b6b91167bdda7fd42ac20fbdb992aeca_5982182900696927448();
        }    
    }

    [UnityEngine.Scripting.Preserve]
    public class CoherenceSync_b6b91167bdda7fd42ac20fbdb992aeca : CoherenceSyncBaked
    {
        private Entity entityId;
        private Logger logger = Coherence.Log.Log.GetLogger<CoherenceSync_b6b91167bdda7fd42ac20fbdb992aeca>();
        
        private global::Y200.ProjectMultiplayer.PlayerMovementManager _b6b91167bdda7fd42ac20fbdb992aeca_6bd53c98d39b449598e18d9535d5a04f_CommandTarget;
        
        
        private IClient client;
        private CoherenceBridge bridge;
        
        private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
        {
			["cdc041b020f744e39048b56d0e860565"] = new Binding_b6b91167bdda7fd42ac20fbdb992aeca_cdc041b020f744e39048b56d0e860565(),
			["1fa34f402c0e419b8ffc7b6cca012abb"] = new Binding_b6b91167bdda7fd42ac20fbdb992aeca_1fa34f402c0e419b8ffc7b6cca012abb(),
			["1c230559e37d486e9cf60c58fb35a31b"] = new Binding_b6b91167bdda7fd42ac20fbdb992aeca_1c230559e37d486e9cf60c58fb35a31b(),
			["dc5513782f19492f99937b038428d61c"] = new Binding_b6b91167bdda7fd42ac20fbdb992aeca_dc5513782f19492f99937b038428d61c(),
			["45618c7f21d04c4c8f52d001cceec88b"] = new Binding_b6b91167bdda7fd42ac20fbdb992aeca_45618c7f21d04c4c8f52d001cceec88b(),
			["7ce3395adfcb4d6ea0475b96cd94994e"] = new Binding_b6b91167bdda7fd42ac20fbdb992aeca_7ce3395adfcb4d6ea0475b96cd94994e(),
			["fdc8af858f7a4243bbf51f0f7ec2c294"] = new Binding_b6b91167bdda7fd42ac20fbdb992aeca_fdc8af858f7a4243bbf51f0f7ec2c294(),
        };
        
        private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings = new Dictionary<string, Action<CommandBinding, CommandsHandler>>();
        
        public CoherenceSync_b6b91167bdda7fd42ac20fbdb992aeca()
        {
            bakedCommandBindings.Add("6bd53c98d39b449598e18d9535d5a04f", BakeCommandBinding__b6b91167bdda7fd42ac20fbdb992aeca_6bd53c98d39b449598e18d9535d5a04f);
        }
        
        public override Binding BakeValueBinding(Binding valueBinding)
        {
            if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
            {
                valueBinding.CloneTo(bakedBinding);
                return bakedBinding;
            }
            
            return null;
        }
        
        public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
            {
                commandBindingBaker.Invoke(commandBinding, commandsHandler);
            }
        }
        private void BakeCommandBinding__b6b91167bdda7fd42ac20fbdb992aeca_6bd53c98d39b449598e18d9535d5a04f(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _b6b91167bdda7fd42ac20fbdb992aeca_6bd53c98d39b449598e18d9535d5a04f_CommandTarget = (global::Y200.ProjectMultiplayer.PlayerMovementManager)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
            	"Y200.ProjectMultiplayer.PlayerMovementManager.UpdateAnimation",
            	"(System.Boolean)",
            	SendCommand__b6b91167bdda7fd42ac20fbdb992aeca_6bd53c98d39b449598e18d9535d5a04f,
            	ReceiveLocalCommand__b6b91167bdda7fd42ac20fbdb992aeca_6bd53c98d39b449598e18d9535d5a04f,
            	MessageTarget.All,
            	_b6b91167bdda7fd42ac20fbdb992aeca_6bd53c98d39b449598e18d9535d5a04f_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__b6b91167bdda7fd42ac20fbdb992aeca_6bd53c98d39b449598e18d9535d5a04f(GenericCommandRequestArgs requestArgs)
        {
            var command = new _b6b91167bdda7fd42ac20fbdb992aeca_6bd53c98d39b449598e18d9535d5a04f();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;

            command.isRunning = (System.Boolean)requestArgs.Args[0];

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__b6b91167bdda7fd42ac20fbdb992aeca_6bd53c98d39b449598e18d9535d5a04f(GenericCommandRequestArgs requestArgs)
        {
            var command = new _b6b91167bdda7fd42ac20fbdb992aeca_6bd53c98d39b449598e18d9535d5a04f();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;

            command.isRunning = (System.Boolean)requestArgs.Args[0];

            ReceiveCommand__b6b91167bdda7fd42ac20fbdb992aeca_6bd53c98d39b449598e18d9535d5a04f(command);
        }

        private void ReceiveCommand__b6b91167bdda7fd42ac20fbdb992aeca_6bd53c98d39b449598e18d9535d5a04f(_b6b91167bdda7fd42ac20fbdb992aeca_6bd53c98d39b449598e18d9535d5a04f command)
        {
            var target = _b6b91167bdda7fd42ac20fbdb992aeca_6bd53c98d39b449598e18d9535d5a04f_CommandTarget;
			target.UpdateAnimation((System.Boolean)(command.isRunning));
        }
        
        public override void ReceiveCommand(IEntityCommand command)
        {
            switch (command)
            {
                case _b6b91167bdda7fd42ac20fbdb992aeca_6bd53c98d39b449598e18d9535d5a04f castedCommand:
                    ReceiveCommand__b6b91167bdda7fd42ac20fbdb992aeca_6bd53c98d39b449598e18d9535d5a04f(castedCommand);
                    break;
                default:
                    logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncReceiveCommandUnhandled,
                        $"CoherenceSync_b6b91167bdda7fd42ac20fbdb992aeca Unhandled command: {command.GetType()}.");
                    break;
            }
        }
        
        public override void CreateEntity(bool usesLodsAtRuntime, string archetypeName, AbsoluteSimulationFrame simFrame, List<ICoherenceComponentData> components)
        {

            if (!usesLodsAtRuntime)
            {
                return;
            }
            
            if (Archetypes.IndexForName.TryGetValue(archetypeName, out int archetypeIndex))
            {
                components.Add(new ArchetypeComponent
                    {
                        index = archetypeIndex,
                        indexSimulationFrame = simFrame,
                        FieldsMask = 0b1
                    }
                );

                return;                
            }
    
            logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncCreateEntityMissingArchetype,
                $"Unable to find archetype {archetypeName} in dictionary. Please, bake manually (coherence > Bake)");
        }
        
        public override void Dispose()
        {
        }
        
        public override void Initialize(Entity entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
        {
            this.logger = logger.With<CoherenceSync_b6b91167bdda7fd42ac20fbdb992aeca>();
            this.bridge = bridge;
            this.entityId = entityId;
            this.client = client;        
        }
    }
}
