// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using Coherence.Toolkit;
    using Coherence.Toolkit.Bindings;
    using Coherence.Entities;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Toolkit.Bindings.ValueBindings;
    using Coherence.Toolkit.Bindings.TransformBindings;
    using Coherence.Connection;
    using Coherence.SimulationFrame;
    using Coherence.Interpolation;
    using Coherence.Log;
    using Logger = Coherence.Log.Logger;
    using UnityEngine.Scripting;
    [UnityEngine.Scripting.Preserve]
    public class Binding_b6b91167bdda7fd42ac20fbdb992aeca_cdc041b020f744e39048b56d0e860565 : PositionBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldPosition);
        public override string CoherenceComponentName => "WorldPosition";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
            set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldPosition)coherenceComponent).value;
            if (!coherenceSync.HasParentWithCoherenceSync) { value += floatingOriginDelta; }

            var simFrame = ((WorldPosition)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldPosition)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldPosition();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_b6b91167bdda7fd42ac20fbdb992aeca_1fa34f402c0e419b8ffc7b6cca012abb : RotationBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldOrientation);
        public override string CoherenceComponentName => "WorldOrientation";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Quaternion Value
        {
            get { return (UnityEngine.Quaternion)(coherenceSync.coherenceRotation); }
            set { coherenceSync.coherenceRotation = (UnityEngine.Quaternion)(value); }
        }

        protected override (UnityEngine.Quaternion value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldOrientation)coherenceComponent).value;

            var simFrame = ((WorldOrientation)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldOrientation)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldOrientation();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_b6b91167bdda7fd42ac20fbdb992aeca_7ce3395adfcb4d6ea0475b96cd94994e : StringBinding
    {   
        private global::UnityEngine.UI.Text CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.UI.Text)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_b6b91167bdda7fd42ac20fbdb992aeca_5313132270030033067);
        public override string CoherenceComponentName => "_b6b91167bdda7fd42ac20fbdb992aeca_5313132270030033067";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.String Value
        {
            get { return (System.String)(CastedUnityComponent.text); }
            set { CastedUnityComponent.text = (System.String)(value); }
        }

        protected override (System.String value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_b6b91167bdda7fd42ac20fbdb992aeca_5313132270030033067)coherenceComponent).text;

            var simFrame = ((_b6b91167bdda7fd42ac20fbdb992aeca_5313132270030033067)coherenceComponent).textSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_b6b91167bdda7fd42ac20fbdb992aeca_5313132270030033067)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.text = Value;
            }
            else
            {
                update.text = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.textSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _b6b91167bdda7fd42ac20fbdb992aeca_5313132270030033067();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_b6b91167bdda7fd42ac20fbdb992aeca_1c80426128cd492da9c89b122f0f8ebe : BoolAnimatorParameterBinding
    {   
        private global::UnityEngine.Animator CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Animator)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_b6b91167bdda7fd42ac20fbdb992aeca_2164096153098260643);
        public override string CoherenceComponentName => "_b6b91167bdda7fd42ac20fbdb992aeca_2164096153098260643";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.GetBool(CastedDescriptor.ParameterHash)); }
            set { CastedUnityComponent.SetBool(CastedDescriptor.ParameterHash, value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_b6b91167bdda7fd42ac20fbdb992aeca_2164096153098260643)coherenceComponent).ToRun;

            var simFrame = ((_b6b91167bdda7fd42ac20fbdb992aeca_2164096153098260643)coherenceComponent).ToRunSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_b6b91167bdda7fd42ac20fbdb992aeca_2164096153098260643)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.ToRun = Value;
            }
            else
            {
                update.ToRun = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.ToRunSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _b6b91167bdda7fd42ac20fbdb992aeca_2164096153098260643();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_b6b91167bdda7fd42ac20fbdb992aeca_06c7002e982d4275869d47d7b2639a37 : ByteBinding
    {   
        private global::Y200.ProjectMultiplayer.PlayerSkinManager CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::Y200.ProjectMultiplayer.PlayerSkinManager)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_b6b91167bdda7fd42ac20fbdb992aeca_4561164196374390466);
        public override string CoherenceComponentName => "_b6b91167bdda7fd42ac20fbdb992aeca_4561164196374390466";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.Byte Value
        {
            get { return (System.Byte)(CastedUnityComponent.CharacterType); }
            set { CastedUnityComponent.CharacterType = (System.Byte)(value); }
        }

        protected override (System.Byte value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_b6b91167bdda7fd42ac20fbdb992aeca_4561164196374390466)coherenceComponent).CharacterType;

            var simFrame = ((_b6b91167bdda7fd42ac20fbdb992aeca_4561164196374390466)coherenceComponent).CharacterTypeSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_b6b91167bdda7fd42ac20fbdb992aeca_4561164196374390466)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.CharacterType = Value;
            }
            else
            {
                update.CharacterType = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.CharacterTypeSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _b6b91167bdda7fd42ac20fbdb992aeca_4561164196374390466();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_b6b91167bdda7fd42ac20fbdb992aeca_a02b4fd6be974c30b0a221eb44ad048b : BoolAnimatorParameterBinding
    {   
        private global::UnityEngine.Animator CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Animator)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_b6b91167bdda7fd42ac20fbdb992aeca_6249753844118996474);
        public override string CoherenceComponentName => "_b6b91167bdda7fd42ac20fbdb992aeca_6249753844118996474";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.GetBool(CastedDescriptor.ParameterHash)); }
            set { CastedUnityComponent.SetBool(CastedDescriptor.ParameterHash, value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_b6b91167bdda7fd42ac20fbdb992aeca_6249753844118996474)coherenceComponent).ToRun;

            var simFrame = ((_b6b91167bdda7fd42ac20fbdb992aeca_6249753844118996474)coherenceComponent).ToRunSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_b6b91167bdda7fd42ac20fbdb992aeca_6249753844118996474)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.ToRun = Value;
            }
            else
            {
                update.ToRun = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.ToRunSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _b6b91167bdda7fd42ac20fbdb992aeca_6249753844118996474();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_b6b91167bdda7fd42ac20fbdb992aeca_098cff1298ed4f3899ee533db7cee438 : BoolAnimatorParameterBinding
    {   
        private global::UnityEngine.Animator CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Animator)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_b6b91167bdda7fd42ac20fbdb992aeca_5597853690678057385);
        public override string CoherenceComponentName => "_b6b91167bdda7fd42ac20fbdb992aeca_5597853690678057385";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.GetBool(CastedDescriptor.ParameterHash)); }
            set { CastedUnityComponent.SetBool(CastedDescriptor.ParameterHash, value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_b6b91167bdda7fd42ac20fbdb992aeca_5597853690678057385)coherenceComponent).ToRun;

            var simFrame = ((_b6b91167bdda7fd42ac20fbdb992aeca_5597853690678057385)coherenceComponent).ToRunSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_b6b91167bdda7fd42ac20fbdb992aeca_5597853690678057385)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.ToRun = Value;
            }
            else
            {
                update.ToRun = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.ToRunSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _b6b91167bdda7fd42ac20fbdb992aeca_5597853690678057385();
        }    
    }

    [UnityEngine.Scripting.Preserve]
    public class CoherenceSync_b6b91167bdda7fd42ac20fbdb992aeca : CoherenceSyncBaked
    {
        private Entity entityId;
        private Logger logger = Coherence.Log.Log.GetLogger<CoherenceSync_b6b91167bdda7fd42ac20fbdb992aeca>();
        
        private global::Y200.ProjectMultiplayer.PlayerSceneManager _b6b91167bdda7fd42ac20fbdb992aeca_a202db9439ec408e8c17770e581736b1_CommandTarget;
        private global::Y200.ProjectMultiplayer.PlayerMessageManager _b6b91167bdda7fd42ac20fbdb992aeca_217c5f05bfa3471ab86e4f32e0f9dc9b_CommandTarget;
        
        
        private IClient client;
        private CoherenceBridge bridge;
        
        private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
        {
			["cdc041b020f744e39048b56d0e860565"] = new Binding_b6b91167bdda7fd42ac20fbdb992aeca_cdc041b020f744e39048b56d0e860565(),
			["1fa34f402c0e419b8ffc7b6cca012abb"] = new Binding_b6b91167bdda7fd42ac20fbdb992aeca_1fa34f402c0e419b8ffc7b6cca012abb(),
			["7ce3395adfcb4d6ea0475b96cd94994e"] = new Binding_b6b91167bdda7fd42ac20fbdb992aeca_7ce3395adfcb4d6ea0475b96cd94994e(),
			["1c80426128cd492da9c89b122f0f8ebe"] = new Binding_b6b91167bdda7fd42ac20fbdb992aeca_1c80426128cd492da9c89b122f0f8ebe(),
			["06c7002e982d4275869d47d7b2639a37"] = new Binding_b6b91167bdda7fd42ac20fbdb992aeca_06c7002e982d4275869d47d7b2639a37(),
			["a02b4fd6be974c30b0a221eb44ad048b"] = new Binding_b6b91167bdda7fd42ac20fbdb992aeca_a02b4fd6be974c30b0a221eb44ad048b(),
			["098cff1298ed4f3899ee533db7cee438"] = new Binding_b6b91167bdda7fd42ac20fbdb992aeca_098cff1298ed4f3899ee533db7cee438(),
        };
        
        private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings = new Dictionary<string, Action<CommandBinding, CommandsHandler>>();
        
        public CoherenceSync_b6b91167bdda7fd42ac20fbdb992aeca()
        {
            bakedCommandBindings.Add("a202db9439ec408e8c17770e581736b1", BakeCommandBinding__b6b91167bdda7fd42ac20fbdb992aeca_a202db9439ec408e8c17770e581736b1);
            bakedCommandBindings.Add("217c5f05bfa3471ab86e4f32e0f9dc9b", BakeCommandBinding__b6b91167bdda7fd42ac20fbdb992aeca_217c5f05bfa3471ab86e4f32e0f9dc9b);
        }
        
        public override Binding BakeValueBinding(Binding valueBinding)
        {
            if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
            {
                valueBinding.CloneTo(bakedBinding);
                return bakedBinding;
            }
            
            return null;
        }
        
        public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
            {
                commandBindingBaker.Invoke(commandBinding, commandsHandler);
            }
        }
        private void BakeCommandBinding__b6b91167bdda7fd42ac20fbdb992aeca_a202db9439ec408e8c17770e581736b1(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _b6b91167bdda7fd42ac20fbdb992aeca_a202db9439ec408e8c17770e581736b1_CommandTarget = (global::Y200.ProjectMultiplayer.PlayerSceneManager)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
            	"Y200.ProjectMultiplayer.PlayerSceneManager.OnSceneChanged",
            	"(System.Byte)",
            	SendCommand__b6b91167bdda7fd42ac20fbdb992aeca_a202db9439ec408e8c17770e581736b1,
            	ReceiveLocalCommand__b6b91167bdda7fd42ac20fbdb992aeca_a202db9439ec408e8c17770e581736b1,
            	MessageTarget.All,
            	_b6b91167bdda7fd42ac20fbdb992aeca_a202db9439ec408e8c17770e581736b1_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__b6b91167bdda7fd42ac20fbdb992aeca_a202db9439ec408e8c17770e581736b1(GenericCommandRequestArgs requestArgs)
        {
            var command = new _b6b91167bdda7fd42ac20fbdb992aeca_a202db9439ec408e8c17770e581736b1();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;

            command.scene = (System.Byte)requestArgs.Args[0];

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__b6b91167bdda7fd42ac20fbdb992aeca_a202db9439ec408e8c17770e581736b1(GenericCommandRequestArgs requestArgs)
        {
            var command = new _b6b91167bdda7fd42ac20fbdb992aeca_a202db9439ec408e8c17770e581736b1();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;

            command.scene = (System.Byte)requestArgs.Args[0];

            ReceiveCommand__b6b91167bdda7fd42ac20fbdb992aeca_a202db9439ec408e8c17770e581736b1(command);
        }

        private void ReceiveCommand__b6b91167bdda7fd42ac20fbdb992aeca_a202db9439ec408e8c17770e581736b1(_b6b91167bdda7fd42ac20fbdb992aeca_a202db9439ec408e8c17770e581736b1 command)
        {
            var target = _b6b91167bdda7fd42ac20fbdb992aeca_a202db9439ec408e8c17770e581736b1_CommandTarget;
			target.OnSceneChanged((System.Byte)(command.scene));
        }
        private void BakeCommandBinding__b6b91167bdda7fd42ac20fbdb992aeca_217c5f05bfa3471ab86e4f32e0f9dc9b(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _b6b91167bdda7fd42ac20fbdb992aeca_217c5f05bfa3471ab86e4f32e0f9dc9b_CommandTarget = (global::Y200.ProjectMultiplayer.PlayerMessageManager)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
            	"Y200.ProjectMultiplayer.PlayerMessageManager.OnMessageSent",
            	"(System.String)",
            	SendCommand__b6b91167bdda7fd42ac20fbdb992aeca_217c5f05bfa3471ab86e4f32e0f9dc9b,
            	ReceiveLocalCommand__b6b91167bdda7fd42ac20fbdb992aeca_217c5f05bfa3471ab86e4f32e0f9dc9b,
            	MessageTarget.All,
            	_b6b91167bdda7fd42ac20fbdb992aeca_217c5f05bfa3471ab86e4f32e0f9dc9b_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__b6b91167bdda7fd42ac20fbdb992aeca_217c5f05bfa3471ab86e4f32e0f9dc9b(GenericCommandRequestArgs requestArgs)
        {
            var command = new _b6b91167bdda7fd42ac20fbdb992aeca_217c5f05bfa3471ab86e4f32e0f9dc9b();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;

            command.completeMessage = (System.String)requestArgs.Args[0];

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__b6b91167bdda7fd42ac20fbdb992aeca_217c5f05bfa3471ab86e4f32e0f9dc9b(GenericCommandRequestArgs requestArgs)
        {
            var command = new _b6b91167bdda7fd42ac20fbdb992aeca_217c5f05bfa3471ab86e4f32e0f9dc9b();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;

            command.completeMessage = (System.String)requestArgs.Args[0];

            ReceiveCommand__b6b91167bdda7fd42ac20fbdb992aeca_217c5f05bfa3471ab86e4f32e0f9dc9b(command);
        }

        private void ReceiveCommand__b6b91167bdda7fd42ac20fbdb992aeca_217c5f05bfa3471ab86e4f32e0f9dc9b(_b6b91167bdda7fd42ac20fbdb992aeca_217c5f05bfa3471ab86e4f32e0f9dc9b command)
        {
            var target = _b6b91167bdda7fd42ac20fbdb992aeca_217c5f05bfa3471ab86e4f32e0f9dc9b_CommandTarget;
			target.OnMessageSent((System.String)(command.completeMessage));
        }
        
        public override void ReceiveCommand(IEntityCommand command)
        {
            switch (command)
            {
                case _b6b91167bdda7fd42ac20fbdb992aeca_a202db9439ec408e8c17770e581736b1 castedCommand:
                    ReceiveCommand__b6b91167bdda7fd42ac20fbdb992aeca_a202db9439ec408e8c17770e581736b1(castedCommand);
                    break;
                case _b6b91167bdda7fd42ac20fbdb992aeca_217c5f05bfa3471ab86e4f32e0f9dc9b castedCommand:
                    ReceiveCommand__b6b91167bdda7fd42ac20fbdb992aeca_217c5f05bfa3471ab86e4f32e0f9dc9b(castedCommand);
                    break;
                default:
                    logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncReceiveCommandUnhandled,
                        $"CoherenceSync_b6b91167bdda7fd42ac20fbdb992aeca Unhandled command: {command.GetType()}.");
                    break;
            }
        }
        
        public override void CreateEntity(bool usesLodsAtRuntime, string archetypeName, AbsoluteSimulationFrame simFrame, List<ICoherenceComponentData> components)
        {

            if (!usesLodsAtRuntime)
            {
                return;
            }
            
            if (Archetypes.IndexForName.TryGetValue(archetypeName, out int archetypeIndex))
            {
                components.Add(new ArchetypeComponent
                    {
                        index = archetypeIndex,
                        indexSimulationFrame = simFrame,
                        FieldsMask = 0b1
                    }
                );

                return;                
            }
    
            logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncCreateEntityMissingArchetype,
                $"Unable to find archetype {archetypeName} in dictionary. Please, bake manually (coherence > Bake)");
        }
        
        public override void Dispose()
        {
        }
        
        public override void Initialize(Entity entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
        {
            this.logger = logger.With<CoherenceSync_b6b91167bdda7fd42ac20fbdb992aeca>();
            this.bridge = bridge;
            this.entityId = entityId;
            this.client = client;        
        }
    }
}
